version: '3'

services:
  github-enterprise-mcp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    command: ["node", "dist/index.js", "--transport", "http"]
    environment:
      - NODE_ENV=production
      - PORT=3000
      - GITHUB_ENTERPRISE_URL=${GITHUB_ENTERPRISE_URL}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - REQUEST_TIMEOUT=${REQUEST_TIMEOUT:-10000}
      - DEBUG=${DEBUG:-false}
    restart: unless-stopped
    volumes:
      - ./.env:/app/.env:ro 